quote remote apps, might contain spaces

diff --git a/libexec/_boxcar b/libexec/_boxcar
--- a/libexec/_boxcar
+++ b/libexec/_boxcar
@@ -224,7 +224,7 @@ function custom_hook {
   logger_info "starting $nm_bootstrap"
   local failed=0
   echo "REMOTE: ssh -F $pth_ssh_config -A default exec ${root_loader:+${root_loader} }env BUILD_IMAGE_PHASE=$BUILD_IMAGE_PHASE OVERRIDE_apps="$OVERRIDE_apps" BUILD_BRANCH=${OVERRIDE_branch} $cache_loaders .boxcar/anchor ${OVERRIDE_anchor} .boxcar/$nm_bootstrap"
-  ssh -F "$pth_ssh_config" -A default "exec ${root_loader:+${root_loader} }env BUILD_IMAGE_PHASE=$BUILD_IMAGE_PHASE OVERRIDE_apps="$OVERRIDE_apps" BUILD_BRANCH=${OVERRIDE_branch} $cache_loaders .boxcar/anchor ${OVERRIDE_anchor} .boxcar/$nm_bootstrap" || failed="$?"
+  ssh -F "$pth_ssh_config" -A default "exec ${root_loader:+${root_loader} }env BUILD_IMAGE_PHASE=$BUILD_IMAGE_PHASE OVERRIDE_apps="$(printf "%q" "$OVERRIDE_apps")" BUILD_BRANCH=${OVERRIDE_branch} $cache_loaders .boxcar/anchor ${OVERRIDE_anchor} .boxcar/$nm_bootstrap" || failed="$?"
   if [[ "$failed" = 0 ]]; then
     logger_info "success! $nm_bootstrap"
 
