enter debug ssh immediately after boxcar failure

diff --git a/libexec/train b/libexec/train
--- a/libexec/train
+++ b/libexec/train
@@ -100,6 +100,10 @@ function build_boxcars {
 }
 
 function build_train {
+  if [[ -f "${SSH_AGENT_FILE:-}" ]]; then
+    source "${SSH_AGENT_FILE}"
+  fi
+
   mark_output
   mark_log "${FLAGS_release}-${FLAGS_provider}"
 
@@ -134,13 +138,27 @@ function build_train {
 
 # entry point
 function main {
+  if [[ -z "${FLAGS_failhook}" ]]; then
+    pth_failhook="$(mktemp -t XXXXXX)"
+  else 
+    pth_failhook="${FLAGS_failhook}"
+  fi
+
   export OVERRIDE_provider="${FLAGS_provider}"
   export OVERRIDE_release="${FLAGS_release}"
   export OVERRIDE_branch="${FLAGS_branch}"
-  if [[ -f "${SSH_AGENT_FILE:-}" ]]; then
-    source "${SSH_AGENT_FILE}"
+  export OVERRIDE_failhook="${pth_failhook}"
+
+  if ! (build_train "$@"); then
+    if [[ -s "$pth_failhook" ]]; then
+      fuglet "debug ssh"
+      bash $pth_failhook || true
+      echo '#' "$cat $pth_failhook"
+      cat $pth_failhook
+    fi
+  elif [[ -z "${FLAGS_failhook}" ]]; then
+    rm -f $pth_failhook
   fi
-  build_train "$@"
 }
 
 require sub "$BASH_SOURCE" "$@"
